export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const SET_LEADING_COMPANY = "SET_LEADING_COMPANY";
export const SET_LATEST_WORK = "SET_LATEST_WORK";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
