export const SET_USER_INFORMATION = "SET_USER_INFORMATION";

export const GET_LIST_EXP = "GET_LIST_EXP";
export const GET_LIST_EDUCATION = "GET_LIST_EDUCATION";
export const GET_LIST_PROJECT = "GET_LIST_PROJECT";
export const GET_LIST_SKILL = "GET_LIST_SKILL";
export const GET_LIST_LANGUAGE = "GET_LIST_LANGUAGE";
export const GET_LIST_CERTIFICATION = "GET_LIST_CERTIFICATION";

export const GET_JOB_APPLY = "GET_JOB_APPLY";
export const GET_JOB_SAVE = "GET_JOB_SAVE";
export const GET_FOLLOW_EMPLOYER = "GET_FOLLOW_EMPLOYER";

export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_EXPECTED_JOB = "UPDATE_EXPECTED_JOB";
export const UPDATE_CAREER_TARGET = "UPDATE_CAREER_TARGET";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_SKILL = "ADD_SKILL";
export const ADD_CERTIFICATION = "ADD_CERTIFICATION";

export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_SKILL = "DELETE_SKILL";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";
export const DELETE_CERTIFICATION = "DELETE_CERTIFICATION";

export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const UPDATE_CERTIFICATION = "UPDATE_CERTIFICATION";
