export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAILURE = "POST_DETAILS_FAILURE";

export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";

export const GET_POSTS_BY_USER = "GET_POSTS_BY_USER";

export const GET_POSTS_SEARCH = "GET_POSTS_SEARCH";

export const DELETE_POST_BY_USER = "DELETE_POST_BY_USER";

export const POST_NEW_WORK = "POST_NEW_WORK";
